### PR TITLE
Exp cheat and opponent 1 HP

### PR DESCRIPTION
**Pull request by MrNbaYoh**
I just added the 1 000 000 EXP cheat and another which set the opponent's HP to 1.

### CODE REVIEW

**Comment by hartmannaf** [comment]
I will check it out later today, but from what I have read it seems good.

**Comment by hartmannaf** [comment]
There seems to be a bug with the 1HP cheat, if you enable it, and battle against a Pokemon, you will fade out after you attacked sucessfully and gained the xp, maybe you could fix it with an check if the value is higher than the target or a button combination.
There seems also be a problem with the new timing and the wild encounter modifier and update dexnav cheat, if you change the route(only if it needs to load it, like through doors or flying, tested with route 103), maybe this is fixable if you add something like speed levels for cheats.
(Only checked it in ORAS)

**Comment by MrNbaYoh** [comment]
I fixed the bug with the 1HP cheat, now it replaces only if the data is greater than 1.
But what is the problem with the dexnav, everything seems to work.

**Comment by hartmannaf** [comment]
I used the random encounter cheat together with the update dexnav cheat, but everytime I used Latios to fly to a route, it crashed. Without the dexnav cheat enabled it worked. This also appeared while changing the route in a way, were it reloads everything(like from route 110 to 103 in oras)

**Comment by MrNbaYoh** [comment]
Well, I made some tests and it is definitively not related with the refresh rate. It crashes with random encounter only , I don't know yet why.

**Comment by hartmannaf** [comment]
Then I will do some testing later today or tomorow, and merge your pr now.
After the problem is found and fixed I will release the next version.

**Comment by hartmannaf** [comment]
was the hp fix already pushed to your fork, or will it need a new pr(since I merged it without asking this before)?

**Comment by MrNbaYoh** [comment]
It was not yet pushed to my fork, I will do it later.

**Pull request merged**
