### PR TITLE
1 HP cheat and DexNav bugs fixed, random encounters improved

### PR DESCRIPTION
**Pull request by MrNbaYoh**
Here is the fix, I hope it will flawlessly work.

### CODE REVIEW

**Comment by hartmannaf** [comment]
I will test it, and after successfully testing it, I will merge it and release the next version.
Thanks for your hard work.

**Comment by hartmannaf** [comment]
It seems the Dexnav won't update correctly on route 103, while route 110 seems to work correctly.
Everything else seems to work correctly.

**Comment by MrNbaYoh** [comment]
The dexnav is not updated when you go to a place without any possible encounter and then return to the previous one. Also when you turn on the cheat, the dexnav is not auto updated, you need to battle or reload the route.

**Comment by hartmannaf** [comment]
I was batteling multiple time and was comming from route 110 at second try. I opend the pokemon list multiple times and it still doesn't seem to work on route 103. There are the wrong pokemon, none of the 6 or more pokemon I caught was shown in dexnav.

**Comment by hartmannaf** [comment]
It seems it was only bad luck, after about 10 pokemon 1 was shown in the dexnav.

**Comment by MrNbaYoh** [comment]
If it is not possible to caught the pokémon the dexnav says you that it does not live there. I am glad to see it works well :)

**Comment by hartmannaf** [comment]
Well there where 6-9 other pokemon, not showing op on the dexnav, but appearing multiple times in the grass. I wasn't changing the route between these pokemon, so there are pokemon that we can encounter but not shown in the dexnav(at least in route 103)

**Comment by MrNbaYoh** [comment]
Yeah, that is what it is supposed to do because all the pokémons cannot be shown in the dexnav.

**Comment by hartmannaf** [comment]
your last answer confused me a bit, that's why I wrote that again, since I thought you said something about not any pokemon appearing in dexnav before.

**Comment by MrNbaYoh** [comment]
Yeah sorry it could be a little bit confusing.

**Comment by MrNbaYoh** [comment]
Yep sorry for that, it was not very clear.

**Pull request merged**
