### PR TITLE
Fixed folders not being created when building repo

### PR DESCRIPTION
**Pull request by theo-meow**
Added a missing feature that caused building to fail of no folders are created.
Fixed this by automatically detecting if the folders are present, and if not, creating them.

### CODE REVIEW

**Comment by Ninjistix** [comment]
altho the game is old, its kinda sad to see some of these projects abandoned 

edit: would it be possible to look into updating the build.py to the latest devkit pro

**Comment by Hartie95** [comment]
I will merge it, after you completed and added the Linux build fixes, you are working on.

**Comment by theo-meow** [comment]
> edit: would it be possible to look into updating the build.py to the latest devkit pro

The project is building in the latest devkitpro (for me at least).
Alltough I am not sure why, since the version is hard-coded into the script.

**Comment by theo-meow** [comment]
This is obsolete, and is now included in Pull Request #32

**Pull request closed without merging**
