### PR TITLE
New shiny cheat

### PR DESCRIPTION
**Pull request by MrNbaYoh**
This adds my new shiny cheat based on RNG PID generation. It allows us to make every pokemon generated shiny (except shiny locked ones I suppose). If you want some details about how it works, ask me.

### CODE REVIEW

**Comment by hartmannaf** [comment]
Thanks for your work, it seems to work perfectly, but what are the exact differences between both shiny cheats, maybe it would be better to remove the old one, or make them or entrys.

**Comment by MrNbaYoh** [comment]
The main difference is that this one is working in any case because the PID is generation is affected. The other one is just replacing the PID of the monster after it was set, and only works during battles.
Well, maybe it would be better to make them "or entries".

**Comment by hartmannaf** [comment]
Thanks I will merge it and update the readme later today or tomorrow. If you want, I will make it an or entry(because of the different categorys it will be only on the program side, not the visual, but I think thats why you said "or entry") while making the release ready.

**Comment by MrNbaYoh** [comment]
Ok thanks. I will write up something on that because it really need to be explained I think.
It would be an occasion to explain the PID generation routine.

**Comment by hartmannaf** [comment]
Now you should be able to edit the wiki(and push to this repo, but please don't push to it directly)
I will create a page for the shiny cheats, where I will paste the text you sended me a time ago about the first shiny cheat.

**Comment by MrNbaYoh** [comment]
Oh, that's cool. I will, of course, not push directly there. I like the pull requests :)
Anyway, thanks.

**Pull request merged**
